/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gofishgame;

/**
 *
 * @author Lily Jennings
 */
public class GameGUI extends javax.swing.JFrame {

    /**
     * Creates new form GameGUI
     */
    public GameGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        P1Card1 = new javax.swing.JLabel();
        P1Card2 = new javax.swing.JLabel();
        P1Card3 = new javax.swing.JLabel();
        GoFishPile = new javax.swing.JLabel();
        P1Card4 = new javax.swing.JLabel();
        P1Card5 = new javax.swing.JLabel();
        P1Card6 = new javax.swing.JLabel();
        P1Card7 = new javax.swing.JLabel();
        P2Card1 = new javax.swing.JLabel();
        P2Card2 = new javax.swing.JLabel();
        P2Card3 = new javax.swing.JLabel();
        AskButton = new javax.swing.JButton();
        PairButton = new javax.swing.JButton();
        P2Card4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(237, 255, 229));

        P1Card1.setText("P1Card1");

        P1Card2.setText("P1Card2");

        P1Card3.setText("P1Card3");

        GoFishPile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b2fh.png"))); // NOI18N
        GoFishPile.setText("Go Fish!");

        P1Card4.setText("P1Card4");

        P1Card5.setText("P1Card5");

        P1Card6.setText("P1Card6");

        P1Card7.setText("P1Card7");

        P2Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png"))); // NOI18N

        P2Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png"))); // NOI18N

        P2Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png"))); // NOI18N

        AskButton.setText("Ask for Card");

        PairButton.setText("Make a Pair");

        P2Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(AskButton)
                        .addGap(78, 78, 78)
                        .addComponent(PairButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GoFishPile)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(P2Card1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(P2Card2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(P2Card3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P2Card4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(P1Card1)
                        .addGap(18, 18, 18)
                        .addComponent(P1Card2)
                        .addGap(18, 18, 18)
                        .addComponent(P1Card3)
                        .addGap(18, 18, 18)
                        .addComponent(P1Card4)
                        .addGap(18, 18, 18)
                        .addComponent(P1Card5)
                        .addGap(18, 18, 18)
                        .addComponent(P1Card6)
                        .addGap(18, 18, 18)
                        .addComponent(P1Card7)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P2Card2)
                    .addComponent(P2Card1)
                    .addComponent(P2Card3)
                    .addComponent(P2Card4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(GoFishPile)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AskButton)
                    .addComponent(PairButton))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1Card1)
                    .addComponent(P1Card2)
                    .addComponent(P1Card3)
                    .addComponent(P1Card4)
                    .addComponent(P1Card5)
                    .addComponent(P1Card6)
                    .addComponent(P1Card7))
                .addGap(96, 96, 96))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AskButton;
    private javax.swing.JLabel GoFishPile;
    private javax.swing.JLabel P1Card1;
    private javax.swing.JLabel P1Card2;
    private javax.swing.JLabel P1Card3;
    private javax.swing.JLabel P1Card4;
    private javax.swing.JLabel P1Card5;
    private javax.swing.JLabel P1Card6;
    private javax.swing.JLabel P1Card7;
    private javax.swing.JLabel P2Card1;
    private javax.swing.JLabel P2Card2;
    private javax.swing.JLabel P2Card3;
    private javax.swing.JLabel P2Card4;
    private javax.swing.JButton PairButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
